// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijdypvmoneruamfpcres.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZHlwdm1vbmVydWFtZnBjcmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDI5OTYsImV4cCI6MjA2NzM3ODk5Nn0.mnMEW9MjEm4_C-6DPHLKrjZtLAvzT95CpnngoFUKKpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});